#!/bin/bash [cite: 2]
# 设置删除键行为 [cite: 2]
stty erase "^?" [cite: 2]
# 检查Realm是否已安装 [cite: 2]
if [ -f "/root/realm/realm" ]; then [cite: 2]
    echo "检测到Realm已安装。" [cite: 2]
    realm_status="已安装" [cite: 2]
    realm_status_color="\033[0;32m" # 绿色 [cite: 2]
else [cite: 2]
    echo "Realm未安装。" [cite: 2]
    realm_status="未安装" [cite: 2]
    realm_status_color="\033[0;31m" # 红色 [cite: 2]
fi [cite: 2]

# 检查Realm服务状态 [cite: 2]
check_realm_service_status() { [cite: 2]
    # 检查转发规则数量 [cite: 2]
    local rule_count=$(grep -c '^\[\[endpoints\]\]' /root/realm/config.toml 2>/dev/null || echo "0") [cite: 2]
    
    if systemctl is-active --quiet realm && [ "$rule_count" -gt 0 ]; [cite: 2]
then [cite: 3]
        echo -e "\033[0;32m启用\033[0m" # 绿色 [cite: 3]
    else [cite: 3]
        echo -e "\033[0;31m未启用\033[0m" # 红色 [cite: 3]
    fi [cite: 3]
} [cite: 3]

# 显示菜单的函数 [cite: 3]
show_menu() { [cite: 3]
    clear [cite: 3]
    echo " "     [cite: 3]
    echo "          欢迎使用Realm一键转发脚本" [cite: 3]
    echo " ———————————— Realm版本v2.7.0 ————————————" [cite: 3]
    echo "     修改by：Ois    修改日期：2025/04/16" [cite: 3]
    echo " " [cite: 3]
    echo "—————————————————————" [cite: 3]
    echo " 1. 安装 Realm" [cite: 4]
    echo "—————————————————————" [cite: 4]
    echo " 2. 添加 Realm 转发规则" [cite: 4]
    echo " 3. 查看 Realm 转发规则" [cite: 4]
    echo " 4. 修改 Realm 转发规则" [cite: 4]
    echo " 5. 删除 Realm 转发规则" [cite: 4]
    echo "—————————————————————" [cite: 4]
    echo " 6. 启动 Realm 服务" [cite: 4]
    echo " 7. 停止 Realm 服务" [cite: 4]
    echo " 8. 重启 Realm 服务" [cite: 4]
    echo "—————————————————————" [cite: 4]
    echo " 9. 卸载 Realm" [cite: 4]
    echo "—————————————————————" [cite: 4]
    echo " 10. 定时重启任务" [cite: 5]
    echo "—————————————————————" [cite: 5]
    echo " 11. 导出转发规则" [cite: 5]
    echo " 12. 导入转发规则" [cite: 5]
    echo "—————————————————————" [cite: 5]
    echo " 0. 退出脚本" [cite: 5]
    echo "—————————————————————" [cite: 5]
    echo " " [cite: 5]
    echo -e "Realm 状态：${realm_status_color}${realm_status}\033[0m" [cite: 5]
    echo -n "Realm 转发状态：" [cite: 5]
    check_realm_service_status [cite: 5]
} [cite: 5]

# 部署环境的函数 [cite: 5]
deploy_realm() { [cite: 5]
    mkdir -p /root/realm [cite: 5]
    cd /root/realm [cite: 5]
    wget -O realm.tar.gz https://github.com/zhboner/realm/releases/download/v2.7.0/realm-x86_64-unknown-linux-gnu.tar.gz [cite: 5]
    tar -xvf realm.tar.gz [cite: 5]
    chmod +x realm [cite: 5]
    # 创建服务文件 [cite: 5]
    echo "[Unit] [cite: 6]
Description=realm [cite: 6]
After=network.target [cite: 6]

[Service] [cite: 6]
Type=simple [cite: 6]
User=root [cite: 6]
Restart=on-failure [cite: 6]
RestartSec=5s [cite: 6]
WorkingDirectory=/root/realm [cite: 6]
ExecStart=/root/realm/realm -c /root/realm/config.toml [cite: 6]

[Install] [cite: 6]
WantedBy=multi-user.target" > /etc/systemd/system/realm.service [cite: 6]
    systemctl daemon-reload [cite: 6]

    # 服务启动后，检查config.toml是否存在，如果不存在则创建 [cite: 6]
    if [ ! -f /root/realm/config.toml ]; then [cite: 7]
        touch /root/realm/config.toml [cite: 7]
    fi [cite: 7]

    # 检查 config.toml 中是否已经包含 [network] 配置块 [cite: 7]
    network_count=$(grep -c '^\[network\]' /root/realm/config.toml) [cite: 7]

    if [ "$network_count" -eq 0 ]; [cite: 7]
then [cite: 8]
        # 如果没有找到 [network]，将其添加到文件顶部 [cite: 8]
        echo "[network] [cite: 8]
no_tcp = false [cite: 8]
use_udp = true [cite: 8]
" | cat - /root/realm/config.toml > temp && mv temp /root/realm/config.toml [cite: 9]
        echo "[network] 配置已添加到 config.toml 文件。" [cite: 9]
    
    elif [ "$network_count" -gt 1 ]; [cite: 9]
then [cite: 10]
        # 如果找到多个 [network]，删除多余的配置块，只保留第一个 [cite: 10]
        sed -i '0,/^\[\[endpoints\]\]/{//!d}' /root/realm/config.toml [cite: 10]
        echo "[network] [cite: 10]
no_tcp = false [cite: 10]
use_udp = true [cite: 10]
" | cat - /root/realm/config.toml > temp && mv temp /root/realm/config.toml [cite: 11]
        echo "多余的 [network] 配置已删除。" [cite: 11]
    else [cite: 11]
        echo "[network] 配置已存在，跳过添加。" [cite: 11]
    fi [cite: 11]

    # 更新realm状态变量 [cite: 11]
    realm_status="已安装" [cite: 11]
    realm_status_color="\033[0;32m" # 绿色 [cite: 11]
    echo "部署完成。" [cite: 11]
} [cite: 11]

# 卸载realm [cite: 11]
uninstall_realm() { [cite: 11]
    systemctl stop realm [cite: 11]
    systemctl disable realm [cite: 11]
    rm -rf /etc/systemd/system/realm.service [cite: 11]
    systemctl daemon-reload [cite: 11]
    rm -rf /root/realm [cite: 11]
    rm -rf "$(pwd)"/realm.sh [cite: 11]
    sed -i '/realm/d' /etc/crontab [cite: 12]
    echo "Realm已被卸载。" [cite: 12]
    # 更新realm状态变量 [cite: 12]
    realm_status="未安装" [cite: 12]
    realm_status_color="\033[0;31m" # 红色 [cite: 12]
} [cite: 12]

# 显示当前所有规则的辅助函数 [cite: 12]
show_current_rules() { [cite: 12]
    # 接收一个参数作为提示消息 [cite: 12]
    local message=${1:-"操作完成"} [cite: 12]
    
    clear [cite: 12]
    echo -e "                      当前 Realm 转发规则                      " [cite: 12]
    echo -e "---------------------------------------------------------------------" [cite: 12]
    local IFS=$'\n' [cite: 13]
    local lines=($(grep -n 'listen =' /root/realm/config.toml 2>/dev/null || echo "")) [cite: 13, 14]
    
    if [ ${#lines[@]} -eq 0 ] || [ -z "$lines" ]; [cite: 14]
then [cite: 15]
        echo -e "没有发现任何转发规则。" [cite: 15]
    else [cite: 15]
        local index=1 [cite: 15]
        for line in "${lines[@]}"; [cite: 15]
do [cite: 16]
            local line_number=$(echo $line | cut -d ':' -f 1) [cite: 16]
            local listen_info=$(sed -n "${line_number}p" /root/realm/config.toml | cut -d '"' -f 2) [cite: 16]
            local remote_info=$(sed -n "$((line_number + 1))p" /root/realm/config.toml | cut -d '"' -f 2) [cite: 16]
            local remark=$(sed -n "$((line_number-1))p" /root/realm/config.toml | grep "^# 备注:" | cut -d ':' -f 2- | sed 's/^ //') [cite: 16]
            
            printf " %-3s | %-12s | %-45s | %-20s\n" "$index" "$listen_info" "$remote_info" "$remark" [cite: 17]
            echo -e "---------------------------------------------------------------------" [cite: 17]
            let index+=1 [cite: 17]
        done [cite: 17]
    fi [cite: 17]
    
    echo -e "\n$message，按回车键返回主菜单..." [cite: 17]
    read  # 等待用户按回车键 [cite: 17]
} [cite: 17]

# 修改转发规则的函数 [cite: 17]
modify_forward() { [cite: 17]
    clear  # 清屏 [cite: 17]
    echo -e "                      当前 Realm 转发规则                      " [cite: 18]
    echo -e "---------------------------------------------------------------------" [cite: 18]
    local IFS=$'\n' # 设置IFS仅以换行符作为分隔符 [cite: 18]
    # 搜索所有包含 [[endpoints]] 的行，表示转发规则的起始行 [cite: 18]
    local lines=($(grep -n '^\[\[endpoints\]\]' /root/realm/config.toml 2>/dev/null || echo "")) [cite: 18, 19]
    
    if [ ${#lines[@]} -eq 0 ] || [ -z "$lines" ]; [cite: 19]
then [cite: 20]
        echo "没有发现任何转发规则。" [cite: 20]
        return [cite: 20]
    fi [cite: 20]

    local index=1 [cite: 20]
    for line in "${lines[@]}"; [cite: 20]
do [cite: 21]
        local line_number=$(echo $line | cut -d ':' -f 1) [cite: 21]
        local remark_line=$((line_number + 1)) [cite: 21]
        local listen_line=$((line_number + 2)) [cite: 21]
        local remote_line=$((line_number + 3)) [cite: 21]

        local remark=$(sed -n "${remark_line}p" /root/realm/config.toml | grep "^# 备注:" | cut -d ':' -f 2- | sed 's/^ //') [cite: 21]
        local listen_info=$(sed -n "${listen_line}p" /root/realm/config.toml | cut -d '"' -f 2) [cite: 21]
        local remote_info=$(sed -n "${remote_line}p" /root/realm/config.toml | cut -d '"' -f 2) [cite: 22]

        printf " %-3s | %-12s | %-45s | %-20s\n" "$index" "$listen_info" "$remote_info" "$remark" [cite: 22]
        echo -e "---------------------------------------------------------------------" [cite: 22]
        let index+=1 [cite: 22]
    done [cite: 22]

    echo "请输入要修改的转发规则序号，取消直接按回车键返回主菜单。" [cite: 22]
    read -e -p "选择: " choice [cite: 22]
    if [ -z "$choice" ]; [cite: 22]
then [cite: 23]
        echo "返回主菜单。" [cite: 23]
        return [cite: 23]
    fi [cite: 23]

    if ! [[ $choice =~ ^[0-9]+$ ]]; then [cite: 24]
        echo "无效输入，请输入数字。" [cite: 24]
        return [cite: 24]
    fi [cite: 24]

    if [ $choice -lt 1 ] || [ $choice -gt ${#lines[@]} ]; then [cite: 25]
        echo "选择超出范围，请输入有效序号。" [cite: 25]
        return [cite: 25]
    fi [cite: 25]

    local chosen_line=${lines[$((choice-1))]} [cite: 25]
    local start_line=$(echo $chosen_line | cut -d ':' -f 1) [cite: 25]
    local remark_line=$((start_line + 1)) [cite: 25]
    local listen_line=$((start_line + 2)) [cite: 25]
    local remote_line=$((start_line + 3)) [cite: 25]

    # 获取当前值 [cite: 25]
    local current_remark=$(sed -n "${remark_line}p" /root/realm/config.toml | grep "^# 备注:" | cut -d ':' -f 2- | sed 's/^ //') [cite: 25]
    local current_listen=$(sed -n "${listen_line}p" /root/realm/config.toml | cut -d '"' -f 2) [cite: 25, 26]
    local current_remote=$(sed -n "${remote_line}p" /root/realm/config.toml | cut -d '"' -f 2) [cite: 26]
    
    # 提取当前的本地端口 [cite: 26]
    local current_local_port=$(echo "$current_listen" | grep -o '[0-9]\+$') [cite: 26]
    
    # 修复IPv6地址解析问题 [cite: 26]
    # 判断是否是IPv6地址（检查是否包含方括号） [cite: 26]
    if [[ "$current_remote" == \[*\]* ]]; [cite: 26]
then [cite: 27]
        # IPv6地址格式：[IPv6地址]:端口 [cite: 27]
        local current_remote_ip=$(echo "$current_remote" | sed -E 's/\[(.*)\]:.*/\1/') [cite: 27]
        local current_remote_port=$(echo "$current_remote" | sed -E 's/.*\]:(.*)/\1/') [cite: 27]
    else [cite: 27]
        # IPv4地址格式：IPv4地址:端口 [cite: 27]
        local current_remote_ip=$(echo "$current_remote" | cut -d ':' -f 1) [cite: 27]
        local current_remote_port=$(echo "$current_remote" | cut -d ':' -f 2) [cite: 27]
    fi [cite: 27]

    echo -e "\n---------------------------------------------------------------------" [cite: 27]
    echo -e "                          当前配置信息                           " [cite: 28]
    echo -e "---------------------------------------------------------------------" [cite: 28]
    echo -e " 本地端口: $current_local_port" [cite: 28]
    echo -e " 远程地址: $current_remote_ip" [cite: 28]
    echo -e " 远程端口: $current_remote_port" [cite: 28]
    echo -e " 转发备注: $current_remark" [cite: 28]
    echo -e "---------------------------------------------------------------------" [cite: 28]
    echo -e "                 请输入新的值（直接回车保持不变）                 " [cite: 29]
    echo -e "---------------------------------------------------------------------" [cite: 29]

    read -e -p " 新的本地端口 [$current_local_port]: " new_local_port [cite: 29]
    read -e -p " 新的远程地址 [$current_remote_ip]: " new_remote_ip [cite: 29]
    read -e -p " 新的远程端口 [$current_remote_port]: " new_remote_port [cite: 29]
    read -e -p " 新的转发备注 [$current_remark]: " new_remark [cite: 29]
    
    # 如果用户没有输入新值，则使用当前值 [cite: 29]
    new_local_port=${new_local_port:-$current_local_port} [cite: 29]
    new_remote_ip=${new_remote_ip:-$current_remote_ip} [cite: 30]
    new_remote_port=${new_remote_port:-$current_remote_port} [cite: 30]
    new_remark=${new_remark:-$current_remark} [cite: 30]
    
    # 处理IPv6地址的特殊格式 [cite: 30]
    if [[ "$new_remote_ip" == \[*\]* ]]; [cite: 30]
then [cite: 31]
        # 已经包含方括号的 IPv6 地址，直接添加端口 [cite: 31]
        remote_format="$new_remote_ip:$new_remote_port" [cite: 31]
    elif [[ "$new_remote_ip" == *:*:* ]]; [cite: 31]
then [cite: 32]
        # 不包含方括号的 IPv6 地址，需要添加方括号 [cite: 32]
        remote_format="[$new_remote_ip]:$new_remote_port" [cite: 32]
    else [cite: 32]
        # IPv4 地址或主机名 [cite: 32]
        remote_format="$new_remote_ip:$new_remote_port" [cite: 32]
    fi [cite: 32]
    
    # 更新配置文件 [cite: 32]
    sed -i "${remark_line}s/^# 备注:.*$/# 备注: $new_remark/" /root/realm/config.toml [cite: 32]
    sed -i "${listen_line}s/listen = \".*\"/listen = \"[::]:$new_local_port\"/" /root/realm/config.toml [cite: 32]
    sed -i "${remote_line}s/remote = \".*\"/remote = \"$remote_format\"/" /root/realm/config.toml [cite: 32]
    
    echo -e "\n---------------------------------------------------------------------" [cite: 32]
    echo -e "                          转发规则已更新                          " [cite: 33]
    echo -e "---------------------------------------------------------------------" [cite: 33]
    
    # 重启服务 [cite: 33]
    sudo systemctl restart realm.service [cite: 33]
    echo "Realm服务已重新启动。" [cite: 33]
    
    # 显示当前规则 [cite: 33]
    show_current_rules "规则修改完成" [cite: 33]
    
    # 使用全局变量避免重复按键 [cite: 34]
    key=1  # 设置一个非空值，使主循环中的read跳过 [cite: 34]
} [cite: 34]



# 删除转发规则的函数 [cite: 34]
delete_forward() { [cite: 34]
    # 标记是否进行了删除操作 [cite: 34]
    local has_deleted=false [cite: 34]
    
    while true; [cite: 34]
do [cite: 35]
        clear  # 清屏，确保每次只显示一个规则列表 [cite: 35]
        echo -e "                      当前 Realm 转发规则                      " [cite: 35]
        echo -e "---------------------------------------------------------------------" [cite: 35]
        local IFS=$'\n' # 设置IFS仅以换行符作为分隔符 [cite: 35]
        # 搜索所有包含 [[endpoints]] 的行，表示转发规则的起始行 [cite: 35]
        local lines=($(grep -n '^\[\[endpoints\]\]' /root/realm/config.toml 2>/dev/null || echo "")) [cite: 36]
        
        if [ ${#lines[@]} -eq 0 ] || [ -z "$lines" ]; then [cite: 36, 37]
            echo "没有发现任何转发规则。" [cite: 37]
            if [ "$has_deleted" = true ]; [cite: 37]
then [cite: 38]
                echo "所有规则已删除，正在重启 Realm 服务以应用更改..." [cite: 38]
                sudo systemctl restart realm.service [cite: 38]
                echo "Realm服务已重新启动。" [cite: 38]
                # 设置标记，避免主循环中重复按键，但不需要显示规则列表 [cite: 38]
                key=1 [cite: 38]
            fi [cite: 39]
            echo "按回车键返回主菜单..." [cite: 39]
            read -e  # 用户只需要按一次回车 [cite: 39]
            return [cite: 39]
        fi [cite: 39]

        local index=1 [cite: 39]
        for line in "${lines[@]}"; [cite: 39]
do [cite: 40]
            local line_number=$(echo $line | cut -d ':' -f 1) [cite: 40]
            local remark_line=$((line_number + 1)) [cite: 40]
            local listen_line=$((line_number + 2)) [cite: 40]
            local remote_line=$((line_number + 3)) [cite: 40]

            local remark=$(sed -n "${remark_line}p" /root/realm/config.toml | grep "^# 备注:" | cut -d ':' -f 2- | sed 's/^ //') [cite: 40]
            local listen_info=$(sed -n "${listen_line}p" /root/realm/config.toml | cut -d '"' -f 2) [cite: 41]
            local remote_info=$(sed -n "${remote_line}p" /root/realm/config.toml | cut -d '"' -f 2) [cite: 41]
            
            printf " %-3s | %-12s | %-45s | %-20s\n" "$index" "$listen_info" "$remote_info" "$remark" [cite: 41]
            echo -e "---------------------------------------------------------------------" [cite: 41]
            let index+=1 [cite: 42]
        done [cite: 42]

        echo "请输入要删除的转发规则序号，取消直接按回车键返回主菜单。" [cite: 42]
        read -e -p "选择: " choice [cite: 42]
        if [ -z "$choice" ]; [cite: 42]
then [cite: 43]
            # 如果有删除操作，则在返回主菜单前重启服务 [cite: 43]
            if [ "$has_deleted" = true ]; [cite: 43]
then [cite: 44]
                echo "正在重启 Realm 服务以应用更改..." [cite: 44]
                sudo systemctl restart realm.service [cite: 44]
                echo "Realm服务已重新启动。" [cite: 44]
                # 设置标记，避免主循环中重复按键，但不需要显示规则列表 [cite: 44]
                key=1 [cite: 44]
            else [cite: 45]
                echo "未进行任何删除操作。" [cite: 45]
            fi [cite: 45]
            return [cite: 45]
        fi [cite: 45]

        if ! [[ $choice =~ ^[0-9]+$ ]]; then [cite: 46]
            echo "无效输入，请输入数字。" [cite: 46]
            continue [cite: 46]
        fi [cite: 46]

        if [ $choice -lt 1 ] || [ $choice -gt ${#lines[@]} ]; then [cite: 47]
            echo "选择超出范围，请输入有效序号。" [cite: 47]
            continue [cite: 47]
        fi [cite: 47]

        local chosen_line=${lines[$((choice-1))]} [cite: 47]
        local start_line=$(echo $chosen_line | cut -d ':' -f 1) [cite: 47]

        # 找到下一个 [[endpoints]] 行，确定删除范围的结束行 [cite: 47]
        local next_endpoints_line=$(grep -n '^\[\[endpoints\]\]' /root/realm/config.toml | grep -A 1 "^$start_line:" | tail -n 1 | cut -d ':' -f 1) [cite: 47, 48]

        if [ -z "$next_endpoints_line" ] || [ "$next_endpoints_line" -le "$start_line" ]; [cite: 48]
then [cite: 49]
            # 如果没有找到下一个 [[endpoints]]，则删除到文件末尾 [cite: 49]
            end_line=$(wc -l < /root/realm/config.toml) [cite: 49]
        else [cite: 49]
            # 如果找到了下一个 [[endpoints]]，则删除到它的前一行 [cite: 49]
            end_line=$((next_endpoints_line - 1)) [cite: 49]
        fi [cite: 49]

        # 使用 sed 删除指定行范围的内容 [cite: 49]
        sed -i "${start_line},${end_line}d" /root/realm/config.toml [cite: 49]

        # 检查并删除可能多余的空行 [cite: 50]
        sed -i '/^\s*$/d' /root/realm/config.toml [cite: 50]

        echo "转发规则及其备注已删除。" [cite: 50]
        
        # 标记已进行删除操作 [cite: 50]
        has_deleted=true [cite: 50]
    done [cite: 50]
} [cite: 50]

# 查看转发规则 [cite: 50]
show_all_conf() { [cite: 50]
    clear  # 清屏 [cite: 50]
    echo -e "                      当前 Realm 转发规则                      " [cite: 50, 51]
    echo -e "---------------------------------------------------------------------" [cite: 51]
    local IFS=$'\n' # 设置IFS仅以换行符作为分隔符 [cite: 51]
    # 搜索所有包含 listen 的行，表示转发规则的起始行 [cite: 51]
    local lines=($(grep -n 'listen =' /root/realm/config.toml 2>/dev/null || echo "")) [cite: 51]
    
    if [ ${#lines[@]} -eq 0 ] || [ -z "$lines" ]; then [cite: 51, 52]
        echo -e "没有发现任何转发规则。" [cite: 52]
        return [cite: 52]
    fi [cite: 52]

    local index=1 [cite: 52]
    for line in "${lines[@]}"; [cite: 52]
do [cite: 53]
        local line_number=$(echo $line | cut -d ':' -f 1) [cite: 53]
        local listen_info=$(sed -n "${line_number}p" /root/realm/config.toml | cut -d '"' -f 2) [cite: 53]
        local remote_info=$(sed -n "$((line_number + 1))p" /root/realm/config.toml | cut -d '"' -f 2) [cite: 53]
        local remark=$(sed -n "$((line_number-1))p" /root/realm/config.toml | grep "^# 备注:" | cut -d ':' -f 2- | sed 's/^ //') [cite: 53]
        
        printf " %-3s | %-12s | %-45s | %-20s\n" "$index" "$listen_info" "$remote_info" "$remark" [cite: 53, 54]
        echo -e "---------------------------------------------------------------------" [cite: 54]
        let index+=1 [cite: 54]
    done [cite: 54]
} [cite: 54]

# 添加转发规则 [cite: 54]
add_forward() { [cite: 54]
    clear  # 清屏 [cite: 54]
    # 先显示当前已经添加的规则列表 [cite: 54]
    echo -e "                      当前 Realm 转发规则                      " [cite: 54]
    echo -e "---------------------------------------------------------------------" [cite: 55]
    local IFS=$'\n' [cite: 55]
    local lines=($(grep -n 'listen =' /root/realm/config.toml 2>/dev/null || echo "")) [cite: 55]
    
    if [ ${#lines[@]} -eq 0 ] || [ -z "$lines" ]; then [cite: 55, 56]
        echo -e "目前没有任何转发规则。" [cite: 56]
    else [cite: 56]
        local index=1 [cite: 56]
        for line in "${lines[@]}"; [cite: 56]
do [cite: 57]
            local line_number=$(echo $line | cut -d ':' -f 1) [cite: 57]
            local listen_info=$(sed -n "${line_number}p" /root/realm/config.toml | cut -d '"' -f 2) [cite: 57]
            local remote_info=$(sed -n "$((line_number + 1))p" /root/realm/config.toml | cut -d '"' -f 2) [cite: 57]
            local remark=$(sed -n "$((line_number-1))p" /root/realm/config.toml | grep "^# 备注:" | cut -d ':' -f 2- | sed 's/^ //') [cite: 57]
            
            printf " %-3s | %-12s | %-45s | %-20s\n" "$index" "$listen_info" "$remote_info" "$remark" [cite: 58]
            echo -e "---------------------------------------------------------------------" [cite: 58]
            let index+=1 [cite: 58]
        done [cite: 58]
    fi [cite: 58]
    
    echo -e "\n现在添加新的转发规则: (取消按回车键返回主菜单)" [cite: 58]
    
    local has_added=false  # 标记是否添加了规则 [cite: 58]
    
    while true; do [cite: 59]
        read -e -p "请输入本地监听端口: " local_port [cite: 59]
        # 如果用户没有输入内容直接按回车，返回主菜单 [cite: 59]
        if [ -z "$local_port" ]; [cite: 59]
then [cite: 60]
            echo "未输入端口，返回主菜单。" [cite: 60]
            # 如果已经添加了规则，需要重启服务 [cite: 60]
            if [ "$has_added" = true ]; [cite: 60]
then [cite: 61]
                sudo systemctl restart realm.service [cite: 61]
                echo "Realm服务已重新启动，转发规则已应用。" [cite: 61]
                # 显示当前规则 [cite: 61]
                show_current_rules "规则添加完成" [cite: 61]
                # 使用全局变量避免重复按键 [cite: 61]
                key=1 [cite: 62]
            fi [cite: 62]
            return [cite: 62]
        fi [cite: 62]
        
        read -e -p "请输入需要转发的IP: " ip [cite: 62]
        # 如果用户没有输入内容直接按回车，返回主菜单 [cite: 62]
        if [ -z "$ip" ]; [cite: 62]
then [cite: 63]
            echo "未输入IP，返回主菜单。" [cite: 63]
            # 如果已经添加了规则，需要重启服务 [cite: 63]
            if [ "$has_added" = true ]; [cite: 63]
then [cite: 64]
                sudo systemctl restart realm.service [cite: 64]
                echo "Realm服务已重新启动，转发规则已应用。" [cite: 64]
                # 显示当前规则 [cite: 64]
                show_current_rules "规则添加完成" [cite: 64]
                # 使用全局变量避免重复按键 [cite: 64]
                key=1 [cite: 65]
            fi [cite: 65]
            return [cite: 65]
        fi [cite: 65]
        
        read -e -p "请输入需要转发端口: " port [cite: 65]
        # 如果用户没有输入内容直接按回车，返回主菜单 [cite: 65]
        if [ -z "$port" ]; [cite: 65]
then [cite: 66]
            echo "未输入转发端口，返回主菜单。" [cite: 66]
            # 如果已经添加了规则，需要重启服务 [cite: 66]
            if [ "$has_added" = true ]; [cite: 66]
then [cite: 67]
                sudo systemctl restart realm.service [cite: 67]
                echo "Realm服务已重新启动，转发规则已应用。" [cite: 67]
                # 显示当前规则 [cite: 67]
                show_current_rules "规则添加完成" [cite: 67]
                # 使用全局变量避免重复按键 [cite: 67]
                key=1 [cite: 68]
            fi [cite: 68]
            return [cite: 68]
        fi [cite: 68]
        
        # 备注可以为空，不做检查 [cite: 68]
        read -e -p "请输入备注(支持中文，可为空): " remark [cite: 68]
        
        # 处理IPv6地址的特殊格式 [cite: 68]
        if [[ "$ip" == \[*\]* ]]; [cite: 68]
then [cite: 69]
            # 已经包含方括号的 IPv6 地址，直接添加端口 [cite: 69]
            remote_format="$ip:$port" [cite: 69]
        elif [[ "$ip" == *:*:* ]]; [cite: 69]
then [cite: 70]
            # 不包含方括号的 IPv6 地址，需要添加方括号 [cite: 70]
            remote_format="[$ip]:$port" [cite: 70]
        else [cite: 70]
            # IPv4 地址或主机名 [cite: 70]
            remote_format="$ip:$port" [cite: 70]
        fi [cite: 70]
        
        # 追加到config.toml文件 [cite: 70]
        echo "[[endpoints]] [cite: 70]
# 备注: $remark [cite: 70]
listen = \"[::]:$local_port\" [cite: 70]
remote = \"$remote_format\"" >> /root/realm/config.toml [cite: 71]
        
        # 标记已添加规则 [cite: 71]
        has_added=true [cite: 71]
        
        read -e -p "是否继续添加(Y/N)? " answer [cite: 71]
        if [[ $answer != "Y" && $answer != "y" ]]; [cite: 71]
then [cite: 72]
            break [cite: 72]
        fi [cite: 72]
        
        # 如果用户选择继续添加，清屏并显示更新后的规则列表 [cite: 72]
        clear [cite: 72]
        echo -e "                      当前 Realm 转发规则                      " [cite: 72, 73]
        echo -e "---------------------------------------------------------------------" [cite: 73]
        local lines=($(grep -n 'listen =' /root/realm/config.toml 2>/dev/null || echo "")) [cite: 73]
        local index=1 [cite: 73]
        for line in "${lines[@]}"; [cite: 73]
do [cite: 74]
            local line_number=$(echo $line | cut -d ':' -f 1) [cite: 74]
            local listen_info=$(sed -n "${line_number}p" /root/realm/config.toml | cut -d '"' -f 2) [cite: 74]
            local remote_info=$(sed -n "$((line_number + 1))p" /root/realm/config.toml | cut -d '"' -f 2) [cite: 74]
            local remark=$(sed -n "$((line_number-1))p" /root/realm/config.toml | grep "^# 备注:" | cut -d ':' -f 2- | sed 's/^ //') [cite: 74]
            
            printf " %-3s | %-12s | %-45s | %-20s\n" "$index" "$listen_info" "$remote_info" "$remark" [cite: 75]
            echo -e "---------------------------------------------------------------------" [cite: 75]
            let index+=1 [cite: 75]
        done [cite: 75]
        echo -e "\n继续添加新的转发规则: (取消按回车键返回主菜单)" [cite: 75]
    done [cite: 75]
    
    # 只有在添加了规则才重启服务 [cite: 75]
    if [ "$has_added" = true ]; then [cite: 76]
        sudo systemctl restart realm.service [cite: 76]
        echo "Realm服务已重新启动，转发规则已应用。" [cite: 76]
        
        # 显示当前所有规则 [cite: 76]
        show_current_rules "规则添加完成" [cite: 76]
        
        # 使用全局变量避免重复按键 [cite: 76]
        key=1  # 设置一个非空值，使主循环中的read跳过 [cite: 76]
    fi [cite: 76]
} [cite: 76]



# 导出转发规则 [cite: 76]
export_rules() { [cite: 76]
    clear [cite: 76]
    echo -e "                      Realm转发规则导出                      " [cite: 77]
    echo -e "---------------------------------------------------------------------" [cite: 77]
    
    local IFS=$'\n' # 设置IFS仅以换行符作为分隔符 [cite: 77]
    
    # 搜索所有包含 [[endpoints]] 的行 [cite: 77]
    local lines=($(grep -n '^\[\[endpoints\]\]' /root/realm/config.toml 2>/dev/null || echo "")) [cite: 77]
    
    if [ ${#lines[@]} -eq 0 ] || [ -z "$lines" ]; then [cite: 77, 78]
        echo "没有发现任何转发规则。" [cite: 78]
        return [cite: 78]
    fi [cite: 78]

    local index=1 [cite: 78]
    for line in "${lines[@]}"; [cite: 78]
do [cite: 79]
        local line_number=$(echo $line | cut -d ':' -f 1) [cite: 79]
        local remark_line=$((line_number + 1)) [cite: 79]
        local listen_line=$((line_number + 2)) [cite: 79]
        local remote_line=$((line_number + 3)) [cite: 79]

        local remark=$(sed -n "${remark_line}p" /root/realm/config.toml | grep "^# 备注:" | cut -d ':' -f 2- | sed 's/^ //') [cite: 79]
        local listen_info=$(sed -n "${listen_line}p" /root/realm/config.toml | cut -d '"' -f 2) [cite: 79]
        local remote_info=$(sed -n "${remote_line}p" /root/realm/config.toml | cut -d '"' -f 2) [cite: 80]

        # 提取本地端口 [cite: 80]
        local local_port=$(echo "$listen_info" | grep -o '[0-9]\+$') [cite: 80]
        
        # 输出格式化的数据行 [cite: 80]
        echo "$index|$local_port|$remote_info|$remark" [cite: 80]
        
        let index+=1 [cite: 80]
    done [cite: 80]
    # 在函数结尾处： [cite: 80]
    echo -e "---------------------------------------------------------------------" [cite: 80]
    echo -e "已导出 $((index-1)) 条转发规则，请复制保存。" [cite: 80, 81]
} [cite: 81]

# 导入转发规则 [cite: 81]
import_rules() { [cite: 81]
    clear [cite: 81]
    echo -e "                      Realm转发规则导入                      " [cite: 81]
    echo -e "---------------------------------------------------------------------" [cite: 81]
    echo -e "请按照以下格式粘贴转发规则：" [cite: 81]
    echo -e "序号|本地端口|远程IP:端口|备注" [cite: 81]
    echo " "   [cite: 81]
    echo -e "例如：" [cite: 81]
    echo -e "1|8080|192.168.1.1:8000|一号服务器" [cite: 81]
    echo -e "2|8443|192.168.1.2:9000|二号服务器" [cite: 82]
    echo -e "3|9000|[2001:db8::1]:8080|IPv6服务器" [cite: 82]
    echo " "   [cite: 82]
    echo -e "---------------------------------------------------------------------" [cite: 82]
    echo -e "请在下方粘贴规则（粘贴完成后按Ctrl+D结束输入）：" [cite: 82]
    
    # 创建临时文件存储用户输入 [cite: 82]
    local temp_file=$(mktemp) [cite: 82]
    
    # 读取用户输入到临时文件 [cite: 82]
    cat > "$temp_file" [cite: 82]
    
    # 获取输入行数 [cite: 82]
    local line_count=$(wc -l < "$temp_file") [cite: 82]
    
    if [ "$line_count" -eq 0 ]; [cite: 82]
then [cite: 83]
        echo "未输入任何规则。" [cite: 83]
        rm "$temp_file" [cite: 83]
        return [cite: 83]
    fi [cite: 83]
    
    # 添加换行，确保与用户输入分开显示 [cite: 83]
    echo -e "\n检测到 $line_count 条规则，准备导入..." [cite: 83]
    read -e -p "是否确认导入？这将添加新的规则，不会覆盖现有规则 (Y/N): " confirm [cite: 83]
    
    if [[ $confirm != "Y" && $confirm != "y" ]]; [cite: 83]
then [cite: 84]
        echo "已取消导入。" [cite: 84]
        rm "$temp_file" [cite: 84]
        return [cite: 84]
    fi [cite: 84]
    
    local success_count=0 [cite: 84]
    
    # 逐行处理导入的数据 [cite: 84]
    while IFS='|' read -r index local_port remote_addr remark || [ -n "$index" ]; [cite: 85]
do [cite: 86]
        # 跳过空行或格式不正确的行 [cite: 86]
        if [ -z "$index" ] || [ -z "$local_port" ] || [ -z "$remote_addr" ]; then [cite: 86, 87]
            continue [cite: 87]
        fi [cite: 87]
        
        # 跳过不以数字开头的行（可能是表头） [cite: 87]
        if ! [[ $index =~ ^[0-9]+$ ]]; then [cite: 88]
            continue [cite: 88]
        fi [cite: 88]
        
        # 处理IPv6地址的格式 [cite: 88]
        if [[ "$remote_addr" != \[*\]* ]] && [[ "$remote_addr" == *:*:* ]]; [cite: 88]
then [cite: 89]
            # 检测到未格式化的IPv6地址（包含多个冒号但不是以[开头） [cite: 89]
            # 尝试提取最后一个冒号后的内容作为端口号 [cite: 89]
            local remote_port="${remote_addr##*:}" [cite: 89]
            # 去除最后一部分（端口号） [cite: 89]
            local remote_ip="${remote_addr%:$remote_port}" [cite: 89]
            # 重新组装为正确的IPv6格式 [cite: 89]
            remote_addr="[$remote_ip]:$remote_port" [cite: 89]
        fi [cite: 89]
        
        # 添加到config.toml [cite: 90]
        echo "[[endpoints]] [cite: 90]
# 备注: $remark [cite: 90]
listen = \"[::]:$local_port\" [cite: 90]
remote = \"$remote_addr\"" >> /root/realm/config.toml [cite: 90]
        
        let success_count+=1 [cite: 90]
    done < "$temp_file" [cite: 90]
    
    rm "$temp_file" [cite: 90]
    
    if [ $success_count -gt 0 ]; [cite: 90]
then [cite: 91]
        echo "成功导入 $success_count 条转发规则。" [cite: 91]
        # 重启服务 [cite: 91]
        sudo systemctl restart realm.service [cite: 91]
        echo "Realm服务已重新启动。" [cite: 91]
        # 显示当前规则 [cite: 91]
        show_current_rules "规则导入完成" [cite: 91]
        # 使用全局变量避免重复按键 [cite: 91]
        key=1 [cite: 91]
    else [cite: 91]
        echo "没有导入任何规则，请检查输入格式是否正确。" [cite: 91]
    fi [cite: 91]
} [cite: 91]

# 自定义显示服务状态的函数 [cite: 91]
show_service_status() { [cite: 91]
    # 检查服务是否活动 [cite: 91]
    if systemctl is-active --quiet realm; then [cite: 92]
        # 服务活动时显示绿色圆点 [cite: 92]
        echo -e "\033[0;32m●\033[0m realm.service - realm" [cite: 92]
    else [cite: 92]
        # 服务不活动时显示红色圆点 [cite: 92]
        echo -e "\033[0;31m●\033[0m realm.service - realm" [cite: 92]
    fi [cite: 92]
    
    # 显示其他状态信息 [cite: 92]
    systemctl status realm.service --no-pager | tail -n +2 | head -n 4 [cite: 92, 93]
} [cite: 93]

# 启动服务 [cite: 93]
start_service() { [cite: 93]
    sudo systemctl unmask realm.service [cite: 93]
    sudo systemctl daemon-reload [cite: 93]
    sudo systemctl restart realm.service [cite: 93]
    sudo systemctl enable realm.service [cite: 93]
    
    # 检查服务是否成功启动 [cite: 93]
    if systemctl is-active --quiet realm; [cite: 93]
then [cite: 94]
        echo -e "\033[0;32mRealm服务已成功启动并设置为开机自启。\033[0m"  # 绿色 [cite: 94]
    else [cite: 94]
        echo -e "\033[0;31mRealm服务启动失败！\033[0m"  # 红色 [cite: 94]
    fi [cite: 94]
    
    echo "Realm 服务状态：" [cite: 94]
    show_service_status [cite: 94]
} [cite: 94]

# 停止服务 [cite: 94]
stop_service() { [cite: 94]
    systemctl stop realm [cite: 94]
    
    # 检查服务是否成功停止 [cite: 94]
    if ! systemctl is-active --quiet realm; then [cite: 95]
        echo -e "\033[0;32mRealm服务已成功停止。\033[0m"  # 绿色 [cite: 95]
    else [cite: 95]
        echo -e "\033[0;31mRealm服务停止失败！\033[0m"  # 红色 [cite: 95]
    fi [cite: 95]
    
    echo "Realm 服务状态：" [cite: 95]
    show_service_status [cite: 95]
} [cite: 95]

# 重启服务 [cite: 95]
restart_service() { [cite: 95]
    sudo systemctl stop realm [cite: 95]
    sudo systemctl unmask realm.service [cite: 95]
    sudo systemctl daemon-reload [cite: 95]
    sudo systemctl restart realm.service [cite: 95]
    sudo systemctl enable realm.service [cite: 95]
    
    # 检查服务是否成功重启 [cite: 95]
    if systemctl is-active --quiet realm; then [cite: 96]
        echo -e "\033[0;32mRealm服务已成功重启。\033[0m"  # 绿色 [cite: 96]
    else [cite: 96]
        echo -e "\033[0;31mRealm服务重启失败！\033[0m"  # 红色 [cite: 96]
    fi [cite: 96]
    
    echo "Realm 服务状态：" [cite: 96]
    show_service_status [cite: 96]
} [cite: 96]

# 定时任务 [cite: 96]
cron_restart() { [cite: 96]
    clear [cite: 96]
    echo -e "---------------------------------------------------------------------" [cite: 96]
    echo -e "                        Realm定时重启任务                         " [cite: 96, 97]
    echo -e "---------------------------------------------------------------------" [cite: 97]
    echo -e "[1] 配置Realm定时重启任务" [cite: 97]
    echo -e "[2] 删除Realm定时重启任务" [cite: 97]
    echo -e "---------------------------------------------------------------------" [cite: 97]
    read -e -p "请选择: " numcron [cite: 97]
    if [ "$numcron" == "1" ]; [cite: 97]
then [cite: 98]
        echo -e "---------------------------------------------------------------------" [cite: 98]
        echo -e "                      Realm定时重启任务类型                      " [cite: 98]
        echo -e "---------------------------------------------------------------------" [cite: 98]
        echo -e "[1] 每？小时重启" [cite: 98]
        echo -e "[2] 每日？点重启" [cite: 98]
        echo -e "---------------------------------------------------------------------" [cite: 99]
        read -e -p "请选择: " numcrontype [cite: 99]
        if [ "$numcrontype" == "1" ]; [cite: 99]
then [cite: 100]
            echo -e "---------------------------------------------------------------------" [cite: 100]
            read -e -p "每？小时重启: " cronhr [cite: 100]
            echo "0 */$cronhr * * * root /usr/bin/systemctl restart realm" >>/etc/crontab [cite: 100]
            echo -e "定时重启设置成功！" [cite: 100]
        elif [ "$numcrontype" == "2" ]; [cite: 100]
then [cite: 101]
            echo -e "---------------------------------------------------------------------" [cite: 101]
            read -e -p "每日？点重启: " cronhr [cite: 101]
            echo "0 $cronhr * * * root /usr/bin/systemctl restart realm" >>/etc/crontab [cite: 101]
            echo -e "定时重启设置成功！" [cite: 101]
        else [cite: 101]
            echo "输入错误，请重试" [cite: 101]
            return [cite: 102]
        fi [cite: 102]
    elif [ "$numcron" == "2" ]; [cite: 102]
then [cite: 103]
        sed -i "/realm/d" /etc/crontab [cite: 103]
        echo -e "定时重启任务删除完成！" [cite: 103]
    else [cite: 103]
        echo "输入错误，请重试" [cite: 103]
        return [cite: 103]
    fi [cite: 103]
} [cite: 103]

# 主循环 [cite: 103]
while true; [cite: 103]
do [cite: 104]
    show_menu [cite: 104]
    read -e -p "请选择一个选项[0-12]: " choice [cite: 104]
    # 去掉输入中的空格 [cite: 104]
    choice=$(echo $choice | tr -d '[:space:]') [cite: 104]

    # 检查输入是否为数字，并在有效范围内 [cite: 104]
    if ! [[ "$choice" =~ ^([0-9]|1[0-2])$ ]]; then [cite: 105]
        echo "无效选项: $choice" [cite: 105]
        continue [cite: 105]
    fi [cite: 105]

    case $choice in [cite: 105]
        1) [cite: 105]
            deploy_realm [cite: 105]
            ;; [cite: 105]
        2) [cite: 106]
            add_forward [cite: 106]
            # 如果key变量有值，说明刚从添加完成界面返回，无需再次等待按键 [cite: 106]
            if [ -n "$key" ]; [cite: 106]
then [cite: 107]
                key=""  # 清空key变量 [cite: 107]
                continue [cite: 107]
            fi [cite: 107]
            ;; [cite: 107]
        3) [cite: 108]
            show_all_conf [cite: 108]
            ;; [cite: 108]
        4) [cite: 109]
            modify_forward [cite: 109]
            # 如果key变量有值，说明刚从修改完成界面返回，无需再次等待按键 [cite: 109]
            if [ -n "$key" ]; [cite: 109]
then [cite: 110]
                key=""  # 清空key变量 [cite: 110]
                continue [cite: 110]
            fi [cite: 110]
            ;; [cite: 110]
        5) [cite: 111]
            delete_forward [cite: 111]
            # 如果key变量有值，说明刚从删除完成界面返回，无需再次等待按键 [cite: 111]
            if [ -n "$key" ]; [cite: 111]
then [cite: 112]
                key=""  # 清空key变量 [cite: 112]
                continue [cite: 112]
            fi [cite: 112]
            ;; [cite: 112]
        6) [cite: 113]
            start_service [cite: 113]
            ;; [cite: 113]
        7) [cite: 114]
            stop_service [cite: 114]
            ;; [cite: 114]
        8) [cite: 115]
            restart_service [cite: 115]
            ;; [cite: 115]
        9) [cite: 116]
            uninstall_realm [cite: 116]
            ;; [cite: 116]
        10) [cite: 117]
            cron_restart [cite: 117]
            ;; [cite: 117]
        11) [cite: 118]
            export_rules [cite: 118]
            ;; [cite: 118]
        12) [cite: 119]
            import_rules [cite: 119]
            # 如果key变量有值，说明刚从导入完成界面返回，无需再次等待按键 [cite: 119]
            if [ -n "$key" ]; [cite: 119]
then [cite: 120]
                key=""  # 清空key变量 [cite: 120]
                continue [cite: 120]
            fi [cite: 120]
            ;; [cite: 120]
        0) [cite: 121]
            echo "退出脚本。"  # 显示退出消息 [cite: 121]
            exit 0            # 退出脚本 [cite: 121]
            ;; [cite: 121]
        *) [cite: 122]
            echo "无效选项: $choice" [cite: 122]
            ;; [cite: 122]
    esac [cite: 123]
    
    # 如果key变量有值，说明刚从某个操作完成界面返回，无需再次等待按键 [cite: 123]
    if [ -n "$key" ]; [cite: 123]
then [cite: 124]
        key=""  # 清空key变量 [cite: 124]
        continue [cite: 124]
    fi [cite: 124]
    
    read -e -p "按任意键返回主菜单..." key [cite: 124]
done [cite: 124]
